version: "3.2"

services:
   
  samba:
    image: lukics/samba:armv7
    command: ["-s", "mount-vevedock-${HOSTNAME};/datavol;yes;no;no", "-u", "lukics;.Techno.", "-pn", "-W"]
    network_mode: host
    container_name: samba
    restart: always
    volumes:
      - /datavol:/datavol
      - /datavol/samba:/etc/samba
    environment:
      - USERID=9001
      - GROUPID=9001

