version: "3.8"

services:

  openhab:
    image: openhab/openhab:${OH_VERSION}
    networks:
      - ha_cluster_lan
    container_name: openhab
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /datavol/openhab-${OH_VERSION}/openhab_addons:/openhab/addons 
      - /datavol/openhab-${OH_VERSION}/openhab_conf:/openhab/conf 
      - /datavol/openhab-${OH_VERSION}/openhab_userdata:/openhab/userdata 
      - /datavol/openhab-${OH_VERSION}/cont-init.d:/etc/cont-init.d
    environment:
      - USER_ID=9001
      - GROUP_ID=9001
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin -Xms400m -Xmx650m 
      - CRYPTO_POLICY=unlimited
    labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.servicePath=/openhab/
      - com.df.reqPathSearch=/openhab
      - com.df.port=8080
  
  frontail:
    image: lukics/frontail:armv7
    networks:
      - ha_cluster_lan
    user: "9001:9001"
    command: ["/openhab/userdata/logs/events.log", "/openhab/userdata/logs/openhab.log"]  
    container_name: frontail
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /datavol/openhab-${OH_VERSION}/openhab_userdata:/openhab/userdata 
      
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    networks:
      - ha_cluster_lan
    user: "9001:9001"
    container_name: ccu
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /datavol/homematic/ccu_data/:/usr/local:rw
      - /lib/modules/:/lib/modules:rw
      - /run/udev/control:/run/udev/control
      - /dev/zero:/dev/ttyACM0
    ports:
      - "8090:80"

      
      
networks:
  ha_cluster_lan:
