version: "3.8"

services:

  influxdb:
    image: influxdb:1.8.9
    container_name: influxdb
    user: "9001:9001"
    command: "-config /etc/influxdb/influxdb.conf"
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - /datavol/influxdb/etc:/etc/influxdb
      - /datavol/influxdb/meta:/var/lib/influxdb/meta
      - /datavol/influxdb/data:/var/lib/influxdb/data
      - /datavol/influxdb/wal:/var/lib/influxdb/wal

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "9001:9001"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /datavol/grafana/etc:/etc/grafana
      - /datavol/grafana/lib:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS:-admin}
      - GF_UID=9001
      - GF_GID=9001
      
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - /datavol/mosquitto:/mosquitto

  ebusd:
    image: lukics/ebusd-3.3:armv7
#    image: john30/ebusd:devel-arm32v7
    container_name: ebusd
    restart: unless-stopped
    ports:
      - 8888:8888
      - 8085:8085
    command: 
      - "-f"
      - "--latency=10000"
      - "--httpport=8085"
      - "--scanconfig" 
      - "--mqtthost=mosquitto"
      - "--mqttport=1883"
      - "--mqttuser=openhab"
      - "--mqttpass=.Techno."
      - "--enablehex"
      - "--device=eBusGW:5000"
      - "--configpath=/etc/ebusd/encon"
      - "--loglevel=info"
      - "--pollinterval=1"
    volumes:
      - /datavol/ebusd/log/:/var/log

  openhab:
    image: openhab/openhab:${OH_VERSION}
    container_name: openhab
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /datavol/openhab-${OH_VERSION}/openhab_addons:/openhab/addons 
      - /datavol/openhab-${OH_VERSION}/openhab_conf:/openhab/conf 
      - /datavol/openhab-${OH_VERSION}/openhab_userdata:/openhab/userdata 
      - /datavol/openhab-${OH_VERSION}/cont-init.d:/etc/cont-init.d
    environment:
      - USER_ID=9001
      - GROUP_ID=9001
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin -Xms400m -Xmx650m 
      - CRYPTO_POLICY=unlimited
    labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.servicePath=/openhab/
      - com.df.reqPathSearch=/openhab
      - com.df.port=8080
  
  frontail:
    image: lukics/frontail:armv7
    container_name: frontail
    user: "9001:9001"
    command: ["/openhab/userdata/logs/events.log", "/openhab/userdata/logs/openhab.log"]  
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /datavol/openhab-${OH_VERSION}/openhab_userdata:/openhab/userdata 
      
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    container_name: ccu
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /datavol/homematic/ccu_data/:/usr/local:rw
      - /lib/modules/:/lib/modules:rw
      - /run/udev/control:/run/udev/control
      - /dev/zero:/dev/ttyACM0
    ports:
      - "8090:80"
      - "8022:22"
      - "2000:2000"
      - "2001:2001"
      - "2002:2002"
      - "2010:2010"
      - "9292:9292"
      - "42000:42000"
      - "42001:42001"
      - "42010:42010"
      - "49292:49292"
      - "8181:8181"
      - "8701:8701"
      - "43439:43439/udp"
