version: "3"

services:

  grafana:
#    image: lukics/grafana:5.4.2
    image: grafana/grafana:latest
    network_mode: host
    restart: always
    volumes:
      - /datavol/grafana/etc:/etc/grafana
      - /datavol/grafana/lib:/var/lib/grafana
    environment:
#      - GF_SERVER_DOMAIN=${DOMAIN:-localhost}
#      - GF_SERVER_DOMAIN=vevedock
#      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS:-admin}
      - GF_UID=9001
      - GF_GID=9001

