version: "3.2"

services:

  openhab:
    image: openhab/openhab:${OH_VERSION}
    network_mode: host
    container_name: openhab
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /datavol/openhab-${OH_VERSION}/openhab_addons:/openhab/addons 
      - /datavol/openhab-${OH_VERSION}/openhab_conf:/openhab/conf 
      - /datavol/openhab-${OH_VERSION}/openhab_userdata:/openhab/userdata 
      - /datavol/openhab-${OH_VERSION}/cont-init.d:/etc/cont-init.d
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin -Xms400m -Xmx650m 
      - CRYPTO_POLICY=unlimited
    labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.servicePath=/openhab/
      - com.df.reqPathSearch=/openhab
      - com.df.port=8080
  
  frontail:
    image: lukics/frontail:armv7
    command: ["/openhab/userdata/logs/events.log", "/openhab/userdata/logs/openhab.log"]  
    network_mode: host
    container_name: frontail
    restart: always
    volumes:
      - /datavol/openhab-${OH_VERSION}/openhab_userdata:/openhab/userdata 
      
