version: "3"

services:

  openhab:
    image: openhab/openhab:${OH_VERSION}
    restart: always
    ports:
      - 80:80
      - 9125:9125
      - 9126:9126
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /datavol/openhab-${OH_VERSION}/openhab_addons:/openhab/addons 
      - /datavol/openhab-${OH_VERSION}/openhab_conf:/openhab/conf 
      - /datavol/openhab-${OH_VERSION}/openhab_userdata:/openhab/userdata 
      - /datavol/openhab-${OH_VERSION}/cont-init.d:/etc/cont-init.d
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin -Xms400m -Xmx650m 
      - CRYPTO_POLICY=unlimited
    labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.servicePath=/openhab/
      - com.df.reqPathSearch=/openhab
      - com.df.port=8080
  
  frontail:
    image: lukics/frontail:armv7
    command: ["/openhab/userdata/logs/events.log", "/openhab/userdata/logs/openhab.log"]  
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /datavol/openhab-${OH_VERSION}/openhab_userdata:/openhab/userdata 
    labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.servicePath=/openhab/
      - com.df.reqPathSearch=/openhab
      - com.df.port=8080
   
  samba:
    image: lukics/samba:armv7
    command: ["-s", "mount-vevedock-${HOSTNAME};/datavol;yes;no;no", "-u", "lukics;.Techno.", "-pn", "-W"]
    restart: always
    ports:
      - 139:139
      - 445:445
    volumes:
      - /datavol:/datavol
    labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.servicePath=/openhab/
      - com.df.reqPathSearch=/openhab
      - com.df.port=8080
   
  networks:
    default:
      external:
        oh_internal
