version: "3"
services:
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    container_name: ccu
    hostname: homematic-raspi
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /datavol/homematic/ccu_data/:/usr/local:rw
      - /datavol/homematic/ccu_data/etc/config/:/etc/config/:rw
    ports:
      - "8090:80"
      - "8022:22"
      - "2001:2001"
      - "2010:2010"
      - "9292:9292"
      - "8181:8181"
