

version: "3"
services:
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    container_name: ccu
    hostname: homematic-raspi
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /datavol/homematic/ccu_data/:/usr/local:rw
      - /lib/modules/:/lib/modules:rw
    ports:
      - "8090:80"
      - "8022:22"
      - "2000:2000"
      - "2001:2001"
      - "2002:2002"
      - "2010:2010"
      - "9292:9292"
      - "42000:42000"
      - "42001:42001"
      - "42010:42010"
      - "49292:49292"
      - "8181:8181"
      - "8701:8701"
      - "43439:43439/udp"
networks:
  nginx_vlan:
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
