version: "3"
services:
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    container_name: ccu
    networks:
      put_net:
          ipv4_address: 192.168.3.200

    hostname: homematic-raspi
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /datavol/homematic/ccu_data/:/usr/local:rw
      - /lib/modules/:/lib/modules:rw
      - /dev/zero:/dev/ttyACM0
networks:
    put_net:
        driver: macvlan
        driver_opts:
            parent: eth0
        ipam:
            config:
                - 
                  subnet: 192.168.3.0/24
                  gateway: 192.168.3.1
