version: "2"
services:
  deconz:
    image: nodered/node-red
    container_name: node-red
    restart: always
    volumes:
      - /datavol/nodered:/data
    ports:
      - 2048:2048
      - 2049:2049
      - 1880:1880
