version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    privileged: true
    restart: unless-stopped
    ports:
    - "8000:8000"
    - "9002:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /datavol/portainer/data:/data
