version: '3.6'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
    - "9002:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /datavol/portainer/data:/data
    networks:
    - iotstack_nw
    
networks:
  iotstack_nw: # Exposed by your host.
    # external: true
    name: IOTstack_Net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.77.60.0/24
        # - gateway: 10.77.60.1
